### ISSUE TITLE
fcm.go incorrect logic

### ISSUE THREAD

**Issue by Bogdamned** [maddevsio/fcm#12]
Hello, just wanted to point out that there is some inconsistency in file **fcm.go** in line **88**:

![image](https://user-images.githubusercontent.com/45657501/75989633-445df800-5efc-11ea-8f04-ce411df74a8e.png)

(resp.StatusCode >= 500 && resp.StatusCode > 600) - this clause will never proccess 5xx statuses, which is this code for (due to commit messsage).

I hope this would help you!

**Comment by gen1us2k** [comment]
Thanks. Fixed condition
