### ISSUE TITLE
support channelID on Android?

### ISSUE THREAD

**Issue by AhmedX6** [maddevsio/fcm#9]
Hello,

Great library thanks.
For improvement : will you support channelids for android ?

Thanks

**Comment by gen1us2k** [comment]
Hello. Sure. We will fix it soon

**Comment by gen1us2k** [comment]
I pushed a fix. Feel free to reopen it if there will be something wrong

**Comment by AhmedX6** [comment]
Excellent I think that should work. :) Thanks for your reactivity !
